AGENTS = [
("01", "mcp-security-gateway", "MCP authorization and policy gateway"),
("02", "agent-action-firewall", "Deterministic action policy enforcement"),
("03", "agent-sandbox-runner", "Restricted execution environment"),
("04", "browser-workflow-agent", "Browser workflow planning and execution"),
("05", "workflow-recorder", "Reusable workflow recording"),
("06", "workflow-generator", "Intent to executable workflow generation"),
("07", "workflow-validator", "Workflow safety and operability validation"),
("08", "agent-observability", "Agent tracing and metrics"),
("09", "agent-evaluation-lab", "Reproducible agent evaluation"),
("10", "agent-replay-debugger", "Recorded run replay"),
("11", "agent-cost-optimizer", "Model and tool cost optimization"),
("12", "agent-memory-optimizer", "Memory classification and compression"),
("13", "prompt-injection-firewall", "External instruction threat detection"),
("14", "tool-discovery-engine", "Least-privilege relevant tool selection"),
("15", "mcp-server-generator", "Schema to MCP tool generation"),
("16", "rest-to-mcp-adapter", "REST endpoint to MCP mapping"),
("17", "agent-approval-center", "Human approval for risky actions"),
("18", "long-running-task-engine", "Durable task lifecycle"),
("19", "agent-failure-recovery", "Retry and alternative-path recovery"),
("20", "agent-security-scanner", "Agent system security scanning"),
]
